{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nxs-anomaly.fullname" . }}
  labels:
    {{- include "nxs-anomaly.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "nxs-anomaly.fullname" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
