{{- if .Values.vaultSecretOperator.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "nxs-anomaly.fullname" . }}
  labels:
    {{- include "nxs-anomaly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vaultSecretOperator.type }}
  mount: {{ required "vaultSecretOperator.mount is required" .Values.vaultSecretOperator.mount }}
  path: {{ required "vaultSecretOperator.path is required" .Values.vaultSecretOperator.path }}
  refreshAfter: {{ .Values.vaultSecretOperator.refreshAfter | quote }}
  {{- with include "nxs-anomaly.vaultAuthRef" . }}
  vaultAuthRef: {{ . }}
  {{- end }}
  destination:
    create: true
    name: {{ include "nxs-anomaly.fullname" . }}
    labels:
      {{- include "nxs-anomaly.labels" . | nindent 6 }}
{{- end }}
