#!/usr/bin/env sh
# Validates a commit message subject against the Conventional Commits convention
# documented in CONTRIBUTING.md. Shared by the local commit-msg hook
# (.githooks/commit-msg) and the CI commitlint job (.gitlab-ci.yml).
#
# Usage:
#   check-commit-msg.sh <file>     # validate the subject in <file>
#   printf '%s' "$msg" | check-commit-msg.sh -   # validate from stdin
set -eu

if [ "${1:-}" = "-" ] || [ -z "${1:-}" ]; then
	subject="$(head -n1)"
else
	subject="$(head -n1 "$1")"
fi

# Merge and revert commits are generated by git; do not enforce a type on them.
case "$subject" in
"Merge "* | "Revert "*) exit 0 ;;
esac

# <type>(<optional scope>)<optional !>: <subject>
pattern='^(feat|fix|perf|refactor|test|docs|chore|ci|build|style)(\([a-z0-9._/-]+\))?(!)?: .+'

if printf '%s' "$subject" | grep -Eq "$pattern"; then
	# Renovate writes the fully-qualified module path into the subject
	# ("chore(deps): update module github.com/klauspost/compress to v1.18.7
	# [security]" — 78 chars), and that path is the whole information content:
	# there is nothing to shorten that a human would not have to look up again.
	# The 72-char rule exists so `git log --oneline` stays readable for commits
	# people write; bot bumps are exempt from the length rule only — the
	# Conventional Commits format above still applies to them.
	case "$subject" in
	"chore(deps): "* | "fix(deps): "*) exit 0 ;;
	esac

	if [ "$(printf '%s' "$subject" | wc -c)" -gt 72 ]; then
		echo "commit-msg: subject longer than 72 chars: $subject" >&2
		exit 1
	fi
	exit 0
fi

echo "commit-msg: invalid subject (Conventional Commits required):" >&2
echo "  $subject" >&2
echo "Expected: <type>(<scope>)?: <subject>" >&2
echo "  e.g. 'fix(engine): bound notification delivery concurrency'" >&2
echo "Types: feat fix perf refactor test docs chore ci build style — see CONTRIBUTING.md" >&2
exit 1
